apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone-deployment
  labels:
    app: devops-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: devops-capstone
    spec:
      containers:
      - name: devops-capstone
        image: weichiet/devops-capstone
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            scheme: HTTP
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
