apiVersion: v1
kind: Service
metadata:
  name: devops-capstone-service
spec:
  selector:
    app: devops-capstone
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
